name: Notify Discord on new/assigned issues
on:
  issues:
    types: [opened, assigned, reopened]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Build and send Discord message
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
          USER_MAP: ${{ secrets.DISCORD_USER_MAP }}
          ACTION: ${{ github.event.action }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          ISSUE_NUM: ${{ github.event.issue.number }}
          ASSIGNEE_LOGIN: ${{ github.event.issue.assignee.login || '' }}
          OPENER_LOGIN: ${{ github.event.issue.user.login }}
          REPO: ${{ github.repository }}
        run: |
          echo "$USER_MAP" > /tmp/user_map.json

          # Resolve Discord mention from GitHub login (falls back to no mention)
          MENTION=""
          if [ -n "$ASSIGNEE_LOGIN" ]; then
            DISCORD_ID=$(jq -r --arg u "$ASSIGNEE_LOGIN" '.[$u] // empty' /tmp/user_map.json)
            if [ -n "$DISCORD_ID" ] && [ "$DISCORD_ID" != "null" ]; then
              MENTION="<@${DISCORD_ID}>"
            fi
          fi

          # Friendly action verb
          case "$ACTION" in
            opened) VERB="opened";;
            assigned) VERB="was assigned";;
            reopened) VERB="reopened";;
            *) VERB="$ACTION";;
          esac

          # Build content
          CONTENT="🧩 **Issue #${ISSUE_NUM}** in **${REPO}** ${VERB}:
**${ISSUE_TITLE}**
${ISSUE_URL}
$([ -n "$MENTION" ] && echo "$MENTION")"

          # Send to Discord
          curl -sS -X POST "$WEBHOOK" \
            -H "Content-Type: application/json" \
            -d "$(jq -n --arg content "$CONTENT" \
                  '{content: $content, allowed_mentions: {parse: ["users"]}}')"
